GO
USE DON_SERGIOS

CREATE TABLE MODELOS
(
ID_MODELO INT IDENTITY (1,1) PRIMARY KEY,
MODELO VARCHAR(50)
)

CREATE TABLE SERVICIOS
(
ID_SERVICIO INT IDENTITY (1,1) PRIMARY KEY,
PROBLEMAS VARCHAR(500),
PRUEBAS VARCHAR(500),
REPUESTOS VARCHAR(200),
PRECIO FLOAT,
OBSERVACIONES VARCHAR(500)
)

CREATE TABLE AUTOS
(
ID_AUTO INT IDENTITY (1,1) PRIMARY KEY,
PATENTE VARCHAR(15),
ID_MODELO INT,
AÑO INT,

CONSTRAINT RELACION_A_MODELOS FOREIGN KEY (ID_MODELO) REFERENCES MODELOS (ID_MODELO)
)

CREATE TABLE CLIENTES
(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOMBRES VARCHAR(100),
APELLIDOS VARCHAR(100),
DIRECCION VARCHAR (100),
TELEFONO INT,
FACEBOOK VARCHAR(100),
ID_AUTO INT,
ID_SERVICIO INT,
FECHA_LLEGADA DATETIME,
FECHA_SALIDA DATETIME,

CONSTRAINT RELACION_A_AUTOS FOREIGN KEY (ID_AUTO) REFERENCES AUTOS (ID_AUTO),
CONSTRAINT RELACION_A_SERVICIOS FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS (ID_SERVICIO)
)


